import type { Dict } from "./ru";

export const kk: Dict = {
  appName: "CRM Omnicomm",
  login: {
    title: "Жүйеге кіру",
    email: "E-mail",
    password: "Құпиясөз",
    submit: "Кіру",
    error: "E-mail немесе құпиясөз қате",
  },
  nav: {
    dashboard: "Басты бет",
    clients: "Клиенттер",
    objects: "Нысандар",
    equipment: "Жабдық",
    sim: "SIM-карталар",
    warehouses: "Қоймалар",
    telematics: "Телематика",
    service: "Сервис",
    billing: "Абоненттік төлем",
    payroll: "Жалақы",
    support: "Қолдау",
    reports: "Есептер",
    logout: "Шығу",
  },
  common: {
    create: "Құру",
    save: "Сақтау",
    cancel: "Болдырмау",
    delete: "Жою",
    search: "Іздеу",
    exportExcel: "Excel-ге жүктеу",
    empty: "Әзірге бос",
    actions: "Әрекеттер",
  },
  clients: {
    title: "Клиенттер",
    name: "Атауы",
    binIin: "БСН/ЖСН",
    legalForm: "Заңды нысаны",
    phone: "Телефон",
    email: "E-mail",
    manager: "Менеджер",
    iik: "ЖСК (IBAN)",
    bik: "БСК",
    kbe: "Кбе",
    vatPayer: "ҚҚС төлеуші",
  },
  objects: {
    title: "Мониторинг нысандары",
    name: "Атауы",
    client: "Клиент",
    kind: "Түрі",
    brandModel: "Маркасы / моделі",
    regNumber: "Мемнөмір",
    vin: "VIN",
  },
  equipment: {
    title: "Жабдық",
    nomenclature: "Номенклатура",
    serial: "Сериялық №",
    imei: "IMEI",
    condition: "Күйі",
    status: "Мәртебесі",
    location: "Орналасуы",
    billingState: "Телематика",
  },
  sim: {
    title: "SIM-карталар",
    importExcel: "Excel-ден импорт",
    importHint: "Оператор файлы: ICCID («Сериялық»), MSISDN («Нөмір»), қалауыңша «Тариф» бағандары. Оператор мен қойма төменде таңдалады.",
    importResult: "Импортталды: {created}, өткізілді (қайталама): {skipped}, қате: {errors}",
    icc: "ICCID",
    msisdn: "Нөмірі (MSISDN)",
    operator: "Оператор",
    plan: "Тарифтік жоспар",
    location: "Орналасуы",
    status: "Мәртебесі",
  },
  warehouses: {
    title: "Қоймалар",
    name: "Атауы",
    type: "Түрі",
    holder: "Ұстаушы",
    supplier: "Жеткізуші",
  },
  telematics: {
    title: "Телематика",
    servers: "Серверлер",
    objects: "Нысан байланыстары",
    syncLog: "Синхрондау журналы",
    blocking: "Бұғаттаулар",
    addServer: "Сервер қосу",
    serverName: "Атауы",
    serverType: "Түрі",
    baseUrl: "API мекенжайы",
    authLogin: "Логин",
    authSecret: "Құпиясөз / секрет",
    health: "Байланыс",
    healthCheckedAt: "Тексерілді",
    checkHealth: "Байланысты тексеру",
    importAction: "Абоненттік базаны импорттау",
    importPreview: "Импортты алдын ала қарау",
    runImport: "Импорттау",
    toCreate: "Құрылады",
    toUpdate: "Жаңартылады",
    totalInSm: "МЖ-дегі барлығы",
    crmObject: "CRM нысаны",
    externalName: "МЖ-дегі атауы",
    externalUuid: "МЖ-дегі UUID",
    syncStatus: "Синхрондау",
    dataReception: "Деректер қабылдау",
    lastSyncedAt: "Синхрондалды",
    conserve: "Консервация",
    resume: "Жалғастыру",
    markDelete: "Жоюға",
    finalDelete: "Біржола жою",
    server: "Сервер",
    operation: "Операция",
    status: "Мәртебесі",
    errorMessage: "Қате",
    errorsOnly: "Тек қателер",
    rules: "Бұғаттау ережелері",
    events: "Бұғаттау журналы",
    addRule: "Ереже қосу",
    scope: "Аумағы",
    scopeDefault: "Әдепкі",
    scopeCategory: "Санат",
    scopeClient: "Клиент",
    advanceGraceDays: "Мерзім ұзарту (аванс), күн",
    creditGraceDays: "Мерзім ұзарту (кредит), күн",
    allowedDebt: "Рұқсат етілген қарыз",
    warnDaysBefore: "Ескерту, күн бұрын",
    manualTitle: "Қолмен бұғаттау / ашу",
    client: "Клиент",
    block: "Бұғаттау",
    unblock: "Бұғаттан шығару",
    unblockUntil: "Мына күнге дейін ашу",
    note: "Түсініктеме",
    debt: "Қарыз",
    performedBy: "Кім орындады",
    auto: "автоматты түрде",
    runAutoBlock: "Автобұғаттауды іске қосу",
    autoBlockDone: "Автобұғаттау орындалды",
  },
  service: {
    title: "Сервис",
    tabRequests: "Өтінімдер",
    tabOrders: "Тапсырыс-нарядтар",
    tabSchedule: "Кесте",
    tabActs: "ТҚ актілері",
    tabTesting: "Тестілеу",
    tabSla: "Нормативтер",
    slaType: "Өтінім түрі",
    slaReaction: "Реакция, мин",
    slaExecution: "Орындау, сағ",
    slaActive: "Қолданыста",
    slaHint: "Жаңа өтінімнің мерзімі норматив бойынша есептеледі; мерзімі өткен өтінімдерді джоб белгілеп, хабарлама жібереді.",
    tabRepairs: "Жөндеу",
    number: "Нөмір",
    client: "Клиент",
    object: "Нысан",
    type: "Түрі",
    priority: "Басымдық",
    status: "Мәртебе",
    performers: "Орындаушылар",
    dueAt: "Мерзімі",
    createdAt: "Құрылды",
    subject: "Тақырып",
    description: "Сипаттама",
    note: "Ескертпе",
    allStatuses: "Барлық мәртебелер",
    allTypes: "Барлық түрлер",
    allClients: "Барлық клиенттер",
    apply: "Қолдану",
    requestsTitle: "ТҚ өтінімдері",
    newRequest: "Жаңа өтінім",
    requestTypes: {
      connect: "Жабдықты қосу",
      dismantle: "Жабдықты бөлшектеу",
      replace: "Жабдықты ауыстыру",
      diagnostics: "Жабдық диагностикасы",
      gps_fault: "GPS-жабдық ақаулығы",
      fuel_sensor_fault: "Отын датчигінің ақаулығы",
      cctv_fault: "Бейнебақылау ақаулығы",
      monitoring_setup: "Мониторингті баптау",
      consultation: "Кеңес беру",
      training: "Клиентті оқыту",
      integration: "Интеграция",
      bi_reporting: "Power BI / есептілік",
      commercial: "Коммерциялық сұраныс",
      payment_question: "Төлем бойынша сұрақ",
      docs_question: "Құжаттар бойынша сұрақ",
      other: "Басқа",
    },
    requestStatuses: {
      new: "Жаңа",
      assigned: "Тағайындалды",
      in_progress: "Жұмыста",
      visit_planned: "Шығу жоспарланды",
      installer_departed: "Монтажшы жолда",
      installer_on_site: "Монтажшы нысанда",
      working: "Жұмыстар орындалуда",
      wait_client: "Клиентті күту",
      wait_parts: "Жабдықты күту",
      completed: "Орындалды",
      in_review: "Тексерілуде",
      closed: "Жабылды",
      overdue: "Мерзімі өтті",
      cancelled: "Болдырылмады",
    },
    priorities: {
      low: "Төмен",
      normal: "Қалыпты",
      high: "Жоғары",
      critical: "Аса маңызды",
    },
    manager: "Менеджер",
    support: "Техқолдау",
    installer: "Техник",
    history: "Тарих",
    changeStatus: "Мәртебені өзгерту",
    resultComment: "Нәтиже-түсініктеме",
    resultCommentRequired: "Жабу үшін нәтиже-түсініктеме міндетті",
    photoRequired: "Фотоесеп қажет",
    photos: "Фотосуреттер",
    uploadPhoto: "Фото жүктеу",
    createOrder: "Тапсырыс-наряд құру",
    ordersTitle: "Тапсырыс-нарядтар",
    newOrder: "Жаңа тапсырыс-наряд",
    address: "Мекенжай",
    scheduledStart: "Жұмыс басталуы",
    scheduledEnd: "Жұмыс аяқталуы",
    orderStatuses: {
      draft: "Жоба",
      planned: "Жоспарланды",
      in_progress: "Жұмыста",
      done: "Орындалды",
      rework: "Пысықтау",
      cancelled: "Болдырылмады",
    },
    fromRequest: "Өтінім бойынша",
    addPerformer: "Орындаушы қосу",
    lead: "аға",
    trips: "Іссапарлар",
    addTrip: "Іссапар қосу",
    transport: "Көлік",
    cost: "Құны",
    includeInCost: "Клиент құнына қосу",
    dateFrom: "Бастап",
    dateTo: "Дейін",
    transferEquipment: "Жабдықты техникке беру",
    technician: "Техник",
    selectUnits: "Жабдық бірліктері",
    transfer: "Беру",
    createAct: "ТҚ актісін құру",
    acts: "ТҚ актілері",
    scheduleTitle: "Тапсырыс-нарядтар кестесі",
    unassigned: "Бөлінбегендер",
    prevWeek: "← Апта",
    nextWeek: "Апта →",
    today: "Бүгін",
    dropHint: "Нарядты сол бағаннан «күн × техник» ұяшығына сүйреңіз",
    noInstallers: "Белсенді техниктер жоқ (installer рөлі)",
    actsTitle: "ТҚ актілері",
    actStatuses: {
      in_preparation: "Дайындалуда",
      done: "Жабылды",
      needs_rework: "Пысықтау",
      cancelled: "Болдырылмады",
    },
    workOrder: "Тапсырыс-наряд",
    performedBy: "Орындаушы",
    lines: "Жабдық",
    addLine: "Жол қосу",
    action: "Әрекет",
    basis: "Негіздеме",
    lineActions: {
      install: "Орнату",
      replace: "Ауыстыру",
      dismantle: "Бөлшектеу",
      diagnostics: "Диагностика",
      service: "Қызмет көрсету",
    },
    bases: {
      sales_order: "Клиент тапсырысы",
      shipped_earlier: "Бұрын жөнелтілген",
      write_off: "Есептен шығару",
      warranty: "Кепілдік",
      testing: "Тестілеу",
      safekeeping: "Жауапты сақтау",
    },
    installedUnit: "Орнатылатын бірлік",
    removedUnit: "Алынатын бірлік",
    works: "Жұмыстар",
    addWork: "Жұмыс қосу",
    workType: "Жұмыс түрі",
    quantity: "Саны",
    rate: "Бағалау",
    amount: "Сома",
    rateOnClose: "бағалау жабу кезінде бекітіледі",
    materials: "Материалдар",
    addMaterial: "Материал қосу",
    fillByNorms: "Нормалар бойынша толтыру",
    byNorm: "норма бойынша",
    simOps: "SIM-операциялар",
    addSimOp: "SIM-операция қосу",
    simInstall: "Орнату",
    simRemove: "Алу",
    closeAct: "Актіні жабу",
    closeActConfirm: "Актіні жабу керек пе? Жабдық қозғалыстары, есептеулер және абоненттік төлем басталады.",
    needsRework: "Пысықтау қажет",
    reworkNote: "Пысықтау себебі",
    testingTitle: "Жабдықты тестілеу",
    newTesting: "Жаңа тестілеу",
    testingStatuses: { open: "Ашық", completed: "Аяқталды", cancelled: "Болдырылмады" },
    daysOnTesting: "Тестте күн",
    startedAt: "Басталды",
    finishedAt: "Аяқталды",
    result: "Нәтиже",
    resultSale: "Сату",
    resultRefusal: "Бас тарту",
    units: "Бірліктер",
    saleConfirm: "Тестті сатумен аяқтау керек пе? Клиент тапсырысы құрылады, жабдық клиентте белсенді абоненттік төлеммен қалады.",
    refusalConfirm: "Тестті бас тартумен аяқтау керек пе? Бөлшектеуге өтінім құрылады.",
    repairsTitle: "Жабдықты жөндеу",
    newRepairDoc: "Жаңа құжат",
    docType: "Құжат түрі",
    repairDocTypes: {
      receive_from_client: "Клиенттен қабылдау",
      send_to_supplier: "Жеткізушіге беру",
      receive_from_supplier: "Жеткізушіден алу",
      issue_to_client: "Клиентке беру",
    },
    repairDocStatuses: { draft: "Жоба", open: "Ашық", closed: "Жабылды", cancelled: "Болдырылмады" },
    supplier: "Жеткізуші",
    warehouse: "Қойма",
    isReplacement: "Ауыстыру қоры",
    defect: "Ақаулық",
    daysOpen: "Ашық күндер",
    closeDoc: "Құжатты жабу",
    equipment: "Жабдық",
    serial: "Сериялық №",
  },
  billing: {
    title: "Абоненттік төлем",
    tabDocuments: "Құжаттар",
    tabRun: "Есептеу",
    tabTariffs: "Тарифтер",
    tabImport: "Төлемдер импорты",
    importTitle: "1С:Бухгалтериядан төлемдер импорты",
    importHint: "Файл: «Есеп шотқа түсімдер» Excel немесе клиент-банк (kl_to_1c.txt). Алдымен алдын ала қарау, өткізу — бөлек батырма. Қайталанулар автоматты түрде алынады.",
    importPreview: "Алдын ала қарау",
    importCommit: "Төлемдерді өткізу",
    tabSettlements: "Ведомость",
    tariffs: "Еркін тарифтер",
    plans: "Тарифтік жоспарлар",
    discounts: "Жеңілдіктер",
    addTariff: "Тариф қосу",
    level: "Деңгей",
    levelDefault: "Әдепкі",
    levelCategory: "Санат",
    levelClient: "Клиент",
    levelObject: "Нысан",
    target: "Мақсат",
    method: "Әдіс",
    methodActivity: "Белсенділік бойынша күнделікті",
    methodSubscription: "Жазылым",
    methodOneTime: "Біржолғы",
    amount: "Сомасы",
    doNotCharge: "Есептемеу",
    validFrom: "Басталуы",
    validTo: "Аяқталуы",
    addPlan: "Жоспар қосу",
    planName: "Жоспар атауы",
    planItems: "Жоспар жолдары",
    itemName: "Жол атауы",
    addItem: "Жол қосу",
    addDiscount: "Жеңілдік қосу",
    discountTotal: "Жеңілдік сомасы",
    discountUsed: "Пайдаланылды",
    active: "Белсенді",
    inactive: "өшірулі",
    runTitle: "Есептеу жүргізу",
    period: "Кезең",
    kind: "Құжат түрі",
    kindAdvance: "Аванстық шоттар",
    kindActs: "Актілер (факт)",
    scheme: "Схема",
    schemeAdvance: "Аванстық",
    schemeCredit: "Кредиттік",
    all: "Барлығы",
    run: "Құжаттарды қалыптастыру",
    runHint: "Таңдалған ай үшін барлық сәйкес белсенді клиенттерге есеп айырысу құжаты қалыптастырылады. Қайта жүргізу құжаттарды қайталамайды.",
    results: "Есептеу нәтижелері",
    resultCreated: "құрылды",
    resultSkipped: "өткізілді",
    reason: "Себебі",
    createdCount: "Құрылды",
    skippedCount: "Өткізілді",
    documents: "Есеп айырысу құжаттары",
    docNumber: "Нөмірі",
    client: "Клиент",
    periodCol: "Кезең",
    subtotal: "Есептелді",
    discount: "Жеңілдік",
    prepaid: "Алдын ала төлем",
    vatAmount: "ҚҚС",
    total: "Барлығы",
    paid: "Төленді",
    status: "Мәртебесі",
    kindAdvanceInvoice: "Шот (аванс)",
    kindAct: "ОЖА",
    kindOneTime: "Шот (біржолғы)",
    statusToAccrue: "есептеуге",
    statusPrepared: "дайындалды",
    statusIssued: "ұсынылды",
    statusSent: "жіберілді",
    statusPartial: "ішінара төлем",
    statusPaid: "төленді",
    statusOverdue: "мерзімі өткен",
    statusCancelled: "жойылды",
    print: "Басып шығару",
    pdfDownload: "PDF жүктеу",
    formInvoice: "Төлемге шот",
    formAct: "Акт (Р-1)",
    formBreakdown: "Таратылым",
    markIssued: "Ұсыну",
    markSent: "Жіберілді",
    cancelDoc: "Құжатты жою",
    cancelConfirm: "Құжат жойылсын ба? Есептеулер жойылады, жеңілдіктер қайтарылады.",
    breakdown: "Нысандар бойынша таратылым",
    object: "Нысан",
    days: "Күндер",
    settlements: "Есеп айырысу ведомосы",
    billed: "Есептелді",
    debt: "Қарыз",
    overpay: "Аванс",
    oldestDue: "Төленбегені",
    addPayment: "Төлем енгізу",
    paymentAmount: "Төлем сомасы",
    paymentMethod: "Төлем әдісі",
    paymentDate: "Төлем күні",
    payBank: "Банк",
    payCash: "Қолма-қол",
    payCard: "Карта",
    payOffset: "Өзара есепке алу",
    linkedDoc: "Құжат (міндетті емес)",
    bankReference: "Төлем тапсырмасы №",
    paymentsJournal: "Төлемдер журналы",
    export1c: "1С-ке жүктеу",
    noCounterparty: "клиенттің контрагенті толтырылмаған",
  },
  payroll: {
    title: "Жалақы",
    tabSheets: "Ведомостар",
    tabEntries: "Есептеулер",
    tabSettings: "Баптаулар",
    categories: "Орындаушы санаттары",
    addCategory: "Санат қосу",
    categoryName: "Атауы",
    note: "Ескертпе",
    assignments: "Санат тағайындаулары",
    assignCategory: "Санат тағайындау",
    performer: "Орындаушы",
    category: "Санат",
    validFrom: "Бастап қолданылады",
    rates: "Жұмыс бағалары",
    addRate: "Баға қосу",
    scope: "Аймақ",
    scopeDefault: "Әдепкі",
    scopeCategory: "Санат",
    scopePerformer: "Орындаушы",
    workType: "Жұмыс түрі",
    rate: "Мөлшерлеме",
    rules: "Төлем ережелері",
    addRule: "Ереже қосу",
    ruleName: "Атауы",
    salary: "Айлық",
    normCount: "Норма, жұмыс",
    pieceOverNorm: "Нормадан тыс кесімді",
    rulesHint: "Айлық кезеңнің алғашқы N жұмысын жабады; «нормадан тыс кесімді» қосылса, N-нен артық жұмыстар кесімді төленеді.",
    active: "Белсенді",
    entriesTitle: "Есептеулер журналы",
    addEntry: "Өтемақы / ұстау",
    kind: "Түрі",
    kinds: { work: "Жұмыс", compensation: "Өтемақы", deduction: "Ұстау" },
    amount: "Сомасы",
    reason: "Негіздеме",
    date: "Күні",
    dateFrom: "Бастап",
    dateTo: "Дейін",
    notInSheet: "Ведомоста жоқ",
    inSheet: "Ведомоста",
    allPerformers: "Барлық орындаушылар",
    allKinds: "Барлық түрлер",
    apply: "Қолдану",
    sheetsTitle: "Ведомостар",
    sheetTitle: "Кесімді табыс ведомосы",
    buildSheet: "Қалыптастыру",
    period: "Кезең",
    month: "Ай",
    preset: "Кезең нұсқасы",
    presetFirstHalf: "1–15",
    presetSecondHalf: "16 — ай соңы",
    presetFullMonth: "Толық ай",
    statuses: { draft: "Жоба", approved: "Бекітілді", paid: "Төленді" },
    actsCount: "Жұмыс",
    workAmount: "Кесімді",
    salaryAmount: "Айлық",
    bonusAmount: "Бонус",
    compensationAmount: "Өтемақылар",
    deductionAmount: "Ұстаулар",
    total: "Барлығы",
    thresholdMet: "Норма",
    yes: "иә",
    no: "жоқ",
    approve: "Бекіту",
    markPaid: "Төленді деп белгілеу",
    cancelSheet: "Жобаны болдырмау",
    cancelConfirm: "Жобаны болдырмау керек пе? Есептеулер босатылып, қайта есептеуге қолжетімді болады.",
    createdBy: "Қалыптастырды",
    createdAt: "Құрылды",
    linesCount: "Жолдар",
    status: "Мәртебе",
  },
  support: {
    title: "Қолдау",
    tabTickets: "Тикеттер",
    tabCalls: "Қоңыраулар",
    tabMessages: "Хабарламалар",
    tabNotifications: "Хабарландырулар",
    ticketsTitle: "Техқолдау тикеттері",
    newTicket: "Жаңа тикет",
    number: "Нөмір",
    client: "Клиент",
    noClient: "Клиентсіз",
    contact: "Байланыс",
    channel: "Арна",
    channels: {
      phone: "Телефон",
      whatsapp: "WhatsApp",
      telegram: "Telegram",
      email: "E-mail",
      site: "Сайт",
      manual: "Қолмен",
      chat: "Чат",
      sms: "SMS",
      web_push: "Push",
    },
    subject: "Тақырып",
    description: "Сипаттама",
    status: "Мәртебе",
    ticketStatuses: {
      new: "Жаңа",
      in_progress: "Жұмыста",
      on_service: "Қызмет көрсетуде",
      done: "Шешілді",
      rejected: "Қабылданбады",
    },
    resolution: "Нәтиже",
    resolutions: {
      remote: "Қашықтан шешілді",
      service_requests: "ТҚ өтінімдері берілді",
      rejected: "Қабылданбады",
    },
    assigned: "Тағайындалған",
    createdAt: "Құрылды",
    closedAt: "Жабылды",
    allStatuses: "Барлық мәртебелер",
    allChannels: "Барлық арналар",
    allClients: "Барлық клиенттер",
    apply: "Қолдану",
    takeInProgress: "Жұмысқа алу",
    resolveRemote: "Қашықтан шешілді",
    remoteConfirm: "Тикетті қашықтан шешілді деп жабу керек пе?",
    toService: "Қызмет көрсетуге беру",
    reject: "Қабылдамау",
    rejectConfirm: "Тикетті қабылдамау керек пе?",
    requestType: "Өтінім түрі",
    selectObjects: "Клиент нысандары",
    createRequests: "Өтінімдер құру",
    needObjects: "Кемінде бір нысан таңдаңыз",
    needClient: "Тикетте клиент көрсетілмеген — қызмет көрсетуге беру мүмкін емес",
    serviceHint: "Таңдалған әр нысан бойынша ТҚ өтінімі құрылады. Тикет «Қызмет көрсетуде» мәртебесіне өтіп, барлық өтінімдер орындалған соң автоматты жабылады.",
    linkedRequests: "Тикет бойынша ТҚ өтінімдері",
    callsTitle: "Қоңыраулар журналы",
    addCall: "Қоңырауды тіркеу",
    direction: "Бағыт",
    directions: { incoming: "Кіріс", outgoing: "Шығыс", missed: "Өткізілген" },
    phone: "Телефон",
    request: "Өтінім",
    durationSec: "Ұзақтығы, сек",
    result: "Нәтиже",
    registeredBy: "Тіркеді",
    messagesTitle: "Хабарламалар журналы",
    addMessage: "Жазба қосу",
    text: "Мәтін",
    directionIn: "Кіріс",
    directionOut: "Шығыс",
    notificationsTitle: "Хабарландырулар",
    tabQueue: "Кезек",
    tabTemplates: "Үлгілер",
    recipient: "Алушы",
    template: "Үлгі",
    attempts: "Әрекеттер",
    lastError: "Қате",
    nextAttemptAt: "Келесі әрекет",
    sentAt: "Жіберілді",
    queueStatuses: {
      queued: "Кезекте",
      sending: "Жіберілуде",
      sent: "Жіберілді",
      failed: "Қате",
      cancelled: "Болдырылмады",
    },
    sendNow: "Қазір жіберу",
    processed: "Өңделді",
    cancelItem: "Болдырмау",
    addTemplate: "Үлгі қосу",
    editTemplate: "Өзгерту",
    code: "Код",
    subjectRu: "Тақырып (RU)",
    subjectKk: "Тақырып (KK)",
    bodyRu: "Мәтін (RU)",
    bodyKk: "Мәтін (KK)",
    active: "Белсенді",
  },
  reports: {
    title: "Есептер",
    tabEquipment: "Жабдық",
    tabDays: "Орналасу күндері",
    tabWorkload: "Жүктеме",
    tabInstallers: "Монтаждаушылар",
    instActive: "Белсенді өтінімдер",
    instDone: "Жабылған актілер",
    instOverdue: "Мерзімі өткен",
    instArrival: "Орт. келу, мин",
    instWork: "Орт. жұмыс, мин",
    instRepeats: "Қайталама шығулар",
    instQuality: "Сапа, %",
    tabActivity: "Белсенділік",
    equipmentTitle: "Жабдық орналасуы бойынша",
    buckets: {
      warehouse: "Қоймалар",
      technician: "Техниктер",
      client: "Клиенттер",
      testing: "Тестілеу",
      supplier: "Жеткізушілер",
      written_off: "Есептен шығарылды",
    },
    group: "Орналасуы",
    bucket: "Топ",
    newCount: "Жаңа",
    usedCount: "Қолданылған",
    total: "Барлығы",
    details: "Таратылым",
    collapse: "Жию",
    daysHere: "Орналасудағы күндер",
    exportDetails: "Таратылымды Excel-ге",
    daysTitle: "Күндер бойынша есептер",
    tabTesting: "Тестілеуде",
    tabFromClients: "Клиенттерден қабылданды",
    tabAtSupplier: "Жеткізушіде",
    doc: "Құжат",
    sinceDate: "Басталған күні",
    days: "Күн",
    defect: "Ақаулық",
    workloadTitle: "Орындаушылар жүктемесі (жоспар/факт)",
    period: "Кезең",
    show: "Көрсету",
    performer: "Орындаушы",
    plannedOrders: "Тағайындалған нарядтар (жоспар)",
    closedActs: "Жабылған актілер (факт)",
    pieceAmount: "Кесімді есептеулер",
    activityTitle: "Клиенттер бойынша жабдық белсенділігі",
    client: "Клиент",
    currentSlice: "Ағымдағы жағдай, дана",
    daysInMonth: "Ай ішіндегі күндер (күй регистрі)",
    nowActive: "Белсенді",
    nowConservation: "Консервация",
    nowDisabled: "Өшірілген",
    activeDays: "Белсенді күндер",
    conservationDays: "Консервация күндері",
    billableDays: "Төленетін күндер",
  },
  dashboard: {
    title: "Басты бет",
    openRequests: "Ашық өтінімдер",
    overdue: "Мерзімі өткендер",
    ordersToday: "Бүгінгі нарядтар",
    openTickets: "Ашық тикеттер",
    syncErrors: "Синхрондау қателері (24 сағ)",
    syncErrorsHint: "Қателер бар — журналды ашу",
    billingMonth: "Ай биллингі",
    billed: "Ұсынылды",
    paid: "Төленді",
    documents: "Құжаттар",
    paidShare: "Жиналымдылық",
    topDebtors: "Топ-5 борышкер",
    debt: "Қарыз",
    allSettlements: "Толық ведомость",
    techBusy: "Техниктердің жүктемесі",
    ordersInWork: "жұмыстағы нарядтар",
    equipmentTitle: "Жабдық",
    eqInstalled: "Орнатылған",
    eqInStock: "Қоймада",
    eqWithTech: "Техниктерде",
    eqTesting: "Тестте",
    eqSupplier: "Жеткізушіде",
    noData: "Деректер жоқ",
  },
  clientCard: {
    scheme: "Есеп айырысу схемасы",
    schemeAdvance: "Аванстық",
    schemeCredit: "Кредиттік",
    category: "Санат",
    manager: "Менеджер",
    requisites: "Деректемелер",
    counterparty: "Контрагент",
    noCounterparty: "Контрагент толтырылмаған",
    legalAddress: "Заңды мекенжай",
    settlements: "Есеп айырысу ведомосы",
    park: "Клиент паркі",
    object: "Нысан",
    equipment: "Жабдық",
    state: "Күйі",
    telematics: "Телематика",
    smName: "МЖ-дегі атауы",
    reception: "Деректер қабылдау",
    recOn: "қосулы",
    recOff: "өшірулі",
    noLink: "байланыс жоқ",
    setState: "Күйді орнату",
    stateActive: "Белсенді",
    stateConservation: "Консервация",
    stateDisabled: "Өшірілген",
    transferClient: "Клиентке ауыстыру",
    moveObject: "Нысанға көшіру",
    targetClient: "Жаңа клиент",
    targetObject: "Нысан",
    apply: "Орындау",
    confirmTransfer: "Жабдықты басқа клиентке ауыстыру керек пе? Биллинг жаңа клиентте жалғасады.",
    confirmMove: "Жабдықты осы клиенттің басқа нысанына көшіру керек пе?",
    syncNote: "Мониторинг жүйесіне команда мүмкіндігінше орындалады; қате синхрондау журналына жазылады.",
    contracts: "Шарттар",
    contractNumber: "Нөмірі",
    kind: "Түрі",
    validFrom: "Бастап",
    validTo: "Дейін",
    status: "Мәртебесі",
    recentDocs: "Соңғы биллинг құжаттары",
    openRequests: "Ашық өтінімдер",
    notFound: "Клиент табылмады",
  },
  profile: {
    language: "Тіл",
  },
  mobile: {
    title: "Техник жұмыс орны",
    brand: "ТЕХНИК",
    navHome: "Басты",
    navOrders: "Нарядтар",
    navStock: "Қойма",
    navPayroll: "Табыс",
    documents: "Құжаттар",
    reports: "Есептер",
    myOrders: "Менің нарядтарым",
    todayShort: "бүгін",
    weekShort: "апта",
    schedule: "Жұмыс кестесі",
    myStock: "Менің қоймам",
    simCards: "SIM-карталар",
    myEarnings: "Менің табысым",
    officeVersion: "Кеңсе нұсқасы",
    logout: "Шығу",
    push: {
      enable: "Хабарламаларды қосу",
      enabled: "Хабарламалар қосулы",
      denied: "Браузерде хабарламаларға тыйым салынған",
      unsupported: "Бұл құрылғыда push қолдау көрсетілмейді",
      error: "Хабарламаларды қосу мүмкін болмады",
    },
    filters: { today: "Бүгін", week: "Апта", all: "Барлығы" },
    order: {
      title: "Наряд",
      client: "Клиент",
      object: "Нысан",
      address: "Мекенжай",
      period: "Кезең",
      note: "Ескертпе",
      request: "Өтінім",
      call: "Қоңырау шалу",
      route2gis: "2ГИС",
      routeGeo: "Карталар",
      performers: "Орындаушылар",
      acts: "ТҚ актілері",
      openAct: "Актіні ашу",
      createAct: "Акт жасау",
      noSchedule: "уақыт тағайындалмаған",
      empty: "Нарядтар жоқ",
    },
    steps: {
      title: "Сапар барысы",
      depart: "Шықтым",
      arrive: "Жеттім",
      start: "Жұмысты бастадым",
      finish: "Аяқтадым",
      cantDo: "Орындай алмаймын",
      cantDoNote: "Себебін көрсетіңіз",
      geoWarn: "Геолокация қолжетімсіз — қадам координатсыз жазылды",
      names: {
        accept: "Қабылданды",
        depart: "Шықты",
        arrive: "Жетті",
        start: "Жұмысты бастады",
        finish: "Аяқтады",
        cant_do: "Орындалмады",
        repeat: "Қайта сапар",
      },
    },
    act: {
      title: "ТҚ актісі",
      main: "Негізгі",
      signerName: "Клиент атынан қол қоюшы",
      signerPlaceholder: "Қол қоюшының аты-жөні",
      saveSigner: "Сақтау",
      photos: "Фототіркеу",
      addPhoto: "Камерадан фото",
      signature: "Клиент қолы",
      drawHint: "Төмендегі өріске саусақпен қол қойыңыз",
      clear: "Тазалау",
      saveSignature: "Қолды сақтау",
      signedAt: "Қол қойылды",
      sendToOffice: "Кеңсеге жіберу",
      sentInfo: "Акт кеңсеге жіберілді. Актіні жабуды кеңсе орындайды — бұл процестің нормасы.",
      notEditable: "Акт енді өңделмейді",
      myUnit: "Өз қоймамнан",
      removedUnit: "Клиенттен алынған",
      forEquipment: "Жабдыққа",
    },
    stock: {
      title: "Менің қоймам",
      equipment: "Жабдық",
      sim: "SIM-карталар",
      empty: "Бос",
    },
    payroll: {
      title: "Менің табысым",
      currentMonth: "Ағымдағы ай",
      prevMonth: "Өткен ай",
      work: "Кесімді жұмыстар",
      compensation: "Өтемақылар",
      deduction: "Ұстап қалулар",
      total: "Барлығы",
      entries: "Есептеулер",
      empty: "Есептеулер жоқ",
    },
  },
};
