export const ru = {
  appName: "CRM Omnicomm",
  login: {
    title: "Вход в систему",
    email: "E-mail",
    password: "Пароль",
    submit: "Войти",
    error: "Неверный e-mail или пароль",
  },
  nav: {
    dashboard: "Главная",
    clients: "Клиенты",
    objects: "Объекты",
    equipment: "Оборудование",
    sim: "SIM-карты",
    warehouses: "Склады",
    telematics: "Телематика",
    service: "Сервис",
    billing: "Абонплата",
    payroll: "Зарплата",
    support: "Поддержка",
    reports: "Отчёты",
    logout: "Выйти",
  },
  common: {
    create: "Создать",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    search: "Поиск",
    exportExcel: "Выгрузить в Excel",
    empty: "Пока пусто",
    actions: "Действия",
  },
  clients: {
    title: "Клиенты",
    name: "Наименование",
    binIin: "БИН/ИИН",
    legalForm: "Юр. форма",
    phone: "Телефон",
    email: "E-mail",
    manager: "Менеджер",
    iik: "ИИК (IBAN)",
    bik: "БИК",
    kbe: "Кбе",
    vatPayer: "Плательщик НДС",
  },
  objects: {
    title: "Объекты мониторинга",
    name: "Наименование",
    client: "Клиент",
    kind: "Вид",
    brandModel: "Марка / модель",
    regNumber: "Госномер",
    vin: "VIN",
  },
  equipment: {
    title: "Оборудование",
    nomenclature: "Номенклатура",
    serial: "Серийный №",
    imei: "IMEI",
    condition: "Состояние",
    status: "Статус",
    location: "Размещение",
    billingState: "Телематика",
  },
  sim: {
    title: "SIM-карты",
    icc: "ICCID",
    msisdn: "Номер (MSISDN)",
    operator: "Оператор",
    plan: "Тарифный план",
    location: "Размещение",
    status: "Статус",
  },
  warehouses: {
    title: "Склады",
    name: "Наименование",
    type: "Тип",
    holder: "Держатель",
    supplier: "Поставщик",
  },
  telematics: {
    title: "Телематика",
    servers: "Серверы",
    objects: "Привязки объектов",
    syncLog: "Журнал синхронизации",
    blocking: "Блокировки",
    addServer: "Добавить сервер",
    serverName: "Наименование",
    serverType: "Тип",
    baseUrl: "Адрес API",
    authLogin: "Логин",
    authSecret: "Пароль / секрет",
    health: "Связь",
    healthCheckedAt: "Проверено",
    checkHealth: "Проверить связь",
    importAction: "Импорт абонбазы",
    importPreview: "Предпросмотр импорта",
    runImport: "Импортировать",
    toCreate: "Будет создано",
    toUpdate: "Будет обновлено",
    totalInSm: "Всего в СМ",
    crmObject: "Объект CRM",
    externalName: "Имя в СМ",
    externalUuid: "UUID в СМ",
    syncStatus: "Синхронизация",
    dataReception: "Приём данных",
    lastSyncedAt: "Синхронизировано",
    conserve: "Консервация",
    resume: "Возобновить",
    markDelete: "К удалению",
    finalDelete: "Удалить окончательно",
    server: "Сервер",
    operation: "Операция",
    status: "Статус",
    errorMessage: "Ошибка",
    errorsOnly: "Только ошибки",
    rules: "Правила блокировки",
    events: "Журнал блокировок",
    addRule: "Добавить правило",
    scope: "Область",
    scopeDefault: "По умолчанию",
    scopeCategory: "Категория",
    scopeClient: "Клиент",
    advanceGraceDays: "Отсрочка (аванс), дн.",
    creditGraceDays: "Отсрочка (кредит), дн.",
    allowedDebt: "Допустимый долг",
    warnDaysBefore: "Предупреждение за, дн.",
    manualTitle: "Ручная блокировка / разблокировка",
    client: "Клиент",
    block: "Заблокировать",
    unblock: "Разблокировать",
    unblockUntil: "Разблокировать до",
    note: "Комментарий",
    debt: "Долг",
    performedBy: "Кто выполнил",
    auto: "автоматически",
    runAutoBlock: "Запустить автоблокировку",
    autoBlockDone: "Автоблокировка выполнена",
  },
  service: {
    title: "Сервис",
    tabRequests: "Заявки",
    tabOrders: "Заказ-наряды",
    tabSchedule: "График",
    tabActs: "Акты ТО",
    tabTesting: "Тестирование",
    tabRepairs: "Ремонт",
    // общие поля
    number: "Номер",
    client: "Клиент",
    object: "Объект",
    type: "Тип",
    priority: "Приоритет",
    status: "Статус",
    performers: "Исполнители",
    dueAt: "Срок",
    createdAt: "Создано",
    subject: "Тема",
    description: "Описание",
    note: "Примечание",
    allStatuses: "Все статусы",
    allTypes: "Все типы",
    allClients: "Все клиенты",
    apply: "Применить",
    // заявки
    requestsTitle: "Заявки ТО",
    newRequest: "Новая заявка",
    requestTypes: {
      connect: "Подключение оборудования",
      dismantle: "Демонтаж оборудования",
      replace: "Замена оборудования",
      diagnostics: "Диагностика оборудования",
      gps_fault: "Неисправность GPS-оборудования",
      fuel_sensor_fault: "Неисправность датчика топлива",
      cctv_fault: "Неисправность видеонаблюдения",
      monitoring_setup: "Настройка мониторинга",
      consultation: "Консультация",
      training: "Обучение клиента",
      integration: "Интеграция",
      bi_reporting: "Power BI / отчётность",
      commercial: "Коммерческий запрос",
      payment_question: "Вопрос по оплате",
      docs_question: "Вопрос по документам",
      other: "Прочее",
    },
    requestStatuses: {
      new: "Новая",
      assigned: "Назначена",
      in_progress: "В работе",
      visit_planned: "Выезд запланирован",
      installer_departed: "Монтажник выехал",
      installer_on_site: "Монтажник на объекте",
      working: "Выполняются работы",
      wait_client: "Ожидание клиента",
      wait_parts: "Ожидание оборудования",
      completed: "Выполнена",
      in_review: "На проверке",
      closed: "Закрыта",
      overdue: "Просрочена",
      cancelled: "Отменена",
    },
    priorities: {
      low: "Низкий",
      normal: "Обычный",
      high: "Высокий",
      critical: "Критический",
    },
    manager: "Менеджер",
    support: "Техподдержка",
    installer: "Техник",
    history: "История",
    changeStatus: "Сменить статус",
    resultComment: "Комментарий-результат",
    resultCommentRequired: "Для закрытия обязателен комментарий-результат",
    photoRequired: "Требуется фотоотчёт",
    photos: "Фотографии",
    uploadPhoto: "Загрузить фото",
    createOrder: "Создать заказ-наряд",
    // заказ-наряды
    ordersTitle: "Заказ-наряды",
    newOrder: "Новый заказ-наряд",
    address: "Адрес",
    scheduledStart: "Начало работ",
    scheduledEnd: "Окончание работ",
    orderStatuses: {
      draft: "Черновик",
      planned: "Запланирован",
      in_progress: "В работе",
      done: "Выполнен",
      rework: "Доработка",
      cancelled: "Отменён",
    },
    fromRequest: "По заявке",
    addPerformer: "Добавить исполнителя",
    lead: "старший",
    trips: "Командировки",
    addTrip: "Добавить командировку",
    transport: "Транспорт",
    cost: "Стоимость",
    includeInCost: "В стоимость клиенту",
    dateFrom: "С",
    dateTo: "По",
    transferEquipment: "Передать оборудование технику",
    technician: "Техник",
    selectUnits: "Единицы оборудования",
    transfer: "Передать",
    createAct: "Создать акт ТО",
    acts: "Акты ТО",
    // график
    scheduleTitle: "График заказ-нарядов",
    unassigned: "Нераспределённые",
    prevWeek: "← Неделя",
    nextWeek: "Неделя →",
    today: "Сегодня",
    dropHint: "Перетащите наряд из левой колонки в ячейку «день × техник»",
    noInstallers: "Нет активных техников (роль installer)",
    // акты
    actsTitle: "Акты ТО",
    actStatuses: {
      in_preparation: "Готовится",
      done: "Закрыт",
      needs_rework: "Доработка",
      cancelled: "Отменён",
    },
    workOrder: "Заказ-наряд",
    performedBy: "Исполнитель",
    lines: "Оборудование",
    addLine: "Добавить строку",
    action: "Действие",
    basis: "Основание",
    lineActions: {
      install: "Установка",
      replace: "Замена",
      dismantle: "Демонтаж",
      diagnostics: "Диагностика",
      service: "Обслуживание",
    },
    bases: {
      sales_order: "Заказ клиента",
      shipped_earlier: "Отгружено ранее",
      write_off: "Списание",
      warranty: "Гарантия",
      testing: "Тестирование",
      safekeeping: "Ответхранение",
    },
    installedUnit: "Устанавливаемая единица",
    removedUnit: "Снимаемая единица",
    works: "Работы",
    addWork: "Добавить работу",
    workType: "Вид работ",
    quantity: "Кол-во",
    rate: "Расценка",
    amount: "Сумма",
    rateOnClose: "расценка фиксируется при закрытии",
    materials: "Материалы",
    addMaterial: "Добавить материал",
    fillByNorms: "Заполнить по нормам",
    byNorm: "по норме",
    simOps: "SIM-операции",
    addSimOp: "Добавить SIM-операцию",
    simInstall: "Установка",
    simRemove: "Снятие",
    closeAct: "Закрыть акт",
    closeActConfirm: "Закрыть акт? Будут созданы движения оборудования, начисления и старт абонплаты.",
    needsRework: "Требуется доработка",
    reworkNote: "Причина доработки",
    // тестирование
    testingTitle: "Тестирование оборудования",
    newTesting: "Новое тестирование",
    testingStatuses: { open: "Открыто", completed: "Завершено", cancelled: "Отменено" },
    daysOnTesting: "Дней на тесте",
    startedAt: "Начато",
    finishedAt: "Завершено",
    result: "Результат",
    resultSale: "Продажа",
    resultRefusal: "Отказ",
    units: "Единицы",
    saleConfirm: "Завершить тест продажей? Будет создан заказ клиента, оборудование останется у клиента с активной абонплатой.",
    refusalConfirm: "Завершить тест отказом? Будет создана заявка на демонтаж.",
    // ремонт
    repairsTitle: "Ремонт оборудования",
    newRepairDoc: "Новый документ",
    docType: "Тип документа",
    repairDocTypes: {
      receive_from_client: "Приём от клиента",
      send_to_supplier: "Передача поставщику",
      receive_from_supplier: "Получение от поставщика",
      issue_to_client: "Выдача клиенту",
    },
    repairDocStatuses: { draft: "Черновик", open: "Открыт", closed: "Закрыт", cancelled: "Отменён" },
    supplier: "Поставщик",
    warehouse: "Склад",
    isReplacement: "Подменный фонд",
    defect: "Неисправность",
    daysOpen: "Дней открыт",
    closeDoc: "Закрыть документ",
    equipment: "Оборудование",
    serial: "Серийный №",
  },
  billing: {
    title: "Абонплата",
    tabDocuments: "Документы",
    tabRun: "Прогон",
    tabTariffs: "Тарифы",
    tabSettlements: "Ведомость",
    // тарифы
    tariffs: "Произвольные тарифы",
    plans: "Тарифные планы",
    discounts: "Скидки",
    addTariff: "Добавить тариф",
    level: "Уровень",
    levelDefault: "По умолчанию",
    levelCategory: "Категория",
    levelClient: "Клиент",
    levelObject: "Объект",
    target: "Цель",
    method: "Метод",
    methodActivity: "Посуточно по активности",
    methodSubscription: "Подписка",
    methodOneTime: "Разовое",
    amount: "Сумма",
    doNotCharge: "Не начислять",
    validFrom: "Действует с",
    validTo: "Действует по",
    addPlan: "Добавить план",
    planName: "Наименование плана",
    planItems: "Строки плана",
    itemName: "Наименование строки",
    addItem: "Добавить строку",
    addDiscount: "Добавить скидку",
    discountTotal: "Сумма скидки",
    discountUsed: "Использовано",
    active: "Активен",
    inactive: "выкл",
    // прогон
    runTitle: "Прогон начислений",
    period: "Период",
    kind: "Тип документов",
    kindAdvance: "Авансовые счета",
    kindActs: "Акты (факт)",
    scheme: "Схема",
    schemeAdvance: "Авансовая",
    schemeCredit: "Кредитная",
    all: "Все",
    run: "Сформировать документы",
    runHint: "По всем подходящим активным клиентам будет сформирован расчётный документ за выбранный месяц. Повторный прогон документы не дублирует.",
    results: "Результаты прогона",
    resultCreated: "создан",
    resultSkipped: "пропущен",
    reason: "Причина",
    createdCount: "Создано",
    skippedCount: "Пропущено",
    // документы
    documents: "Расчётные документы",
    docNumber: "Номер",
    client: "Клиент",
    periodCol: "Период",
    subtotal: "Начислено",
    discount: "Скидка",
    prepaid: "Предоплата",
    vatAmount: "НДС",
    total: "Итого",
    paid: "Оплачено",
    status: "Статус",
    kindAdvanceInvoice: "Счёт (аванс)",
    kindAct: "АВР",
    kindOneTime: "Счёт (разовый)",
    statusToAccrue: "к начислению",
    statusPrepared: "подготовлен",
    statusIssued: "выставлен",
    statusSent: "отправлен",
    statusPartial: "частичная оплата",
    statusPaid: "оплачен",
    statusOverdue: "просрочен",
    statusCancelled: "отменён",
    print: "Печать",
    pdfDownload: "Скачать PDF",
    formInvoice: "Счёт на оплату",
    formAct: "Акт (Р-1)",
    formBreakdown: "Расшифровка",
    markIssued: "Выставить",
    markSent: "Отправлен",
    cancelDoc: "Отменить документ",
    cancelConfirm: "Отменить документ? Начисления будут аннулированы, скидки возвращены.",
    breakdown: "Расшифровка по объектам",
    object: "Объект",
    days: "Дни",
    // оплаты и ведомость
    settlements: "Ведомость расчётов",
    billed: "Начислено",
    debt: "Долг",
    overpay: "Аванс",
    oldestDue: "Неоплачено с",
    addPayment: "Ввести оплату",
    paymentAmount: "Сумма оплаты",
    paymentMethod: "Метод оплаты",
    paymentDate: "Дата оплаты",
    payBank: "Банк",
    payCash: "Наличные",
    payCard: "Карта",
    payOffset: "Взаимозачёт",
    linkedDoc: "Документ (необязательно)",
    bankReference: "Платёжное поручение №",
    paymentsJournal: "Журнал оплат",
    export1c: "Выгрузка в 1С",
    noCounterparty: "у клиента не заполнен контрагент",
  },
  payroll: {
    title: "Зарплата",
    tabSheets: "Ведомости",
    tabEntries: "Начисления",
    tabSettings: "Настройки",
    // настройки: категории
    categories: "Категории исполнителей",
    addCategory: "Добавить категорию",
    categoryName: "Наименование",
    note: "Примечание",
    assignments: "Назначения категорий",
    assignCategory: "Назначить категорию",
    performer: "Исполнитель",
    category: "Категория",
    validFrom: "Действует с",
    // настройки: расценки
    rates: "Расценки на работы",
    addRate: "Добавить расценку",
    scope: "Область",
    scopeDefault: "По умолчанию",
    scopeCategory: "Категория",
    scopePerformer: "Исполнитель",
    workType: "Вид работ",
    rate: "Ставка",
    // настройки: правила
    rules: "Правила оплаты",
    addRule: "Добавить правило",
    ruleName: "Наименование",
    salary: "Оклад",
    normCount: "Норма, работ",
    pieceOverNorm: "Сделка сверх нормы",
    rulesHint: "Оклад покрывает первые N работ периода; при включённой «сделке сверх нормы» работы сверх N оплачиваются сдельно.",
    active: "Активно",
    // журнал начислений
    entriesTitle: "Журнал начислений",
    addEntry: "Компенсация / удержание",
    kind: "Вид",
    kinds: { work: "Работа", compensation: "Компенсация", deduction: "Удержание" },
    amount: "Сумма",
    reason: "Основание",
    date: "Дата",
    dateFrom: "С",
    dateTo: "По",
    notInSheet: "Не в ведомости",
    inSheet: "В ведомости",
    allPerformers: "Все исполнители",
    allKinds: "Все виды",
    apply: "Применить",
    // ведомости
    sheetsTitle: "Ведомости",
    sheetTitle: "Ведомость по сдельному заработку",
    buildSheet: "Сформировать",
    period: "Период",
    month: "Месяц",
    preset: "Вариант периода",
    presetFirstHalf: "1–15",
    presetSecondHalf: "16 — конец месяца",
    presetFullMonth: "Полный месяц",
    statuses: { draft: "Черновик", approved: "Утверждена", paid: "Выплачена" },
    actsCount: "Работ",
    workAmount: "Сделка",
    salaryAmount: "Оклад",
    bonusAmount: "Бонус",
    compensationAmount: "Компенсации",
    deductionAmount: "Удержания",
    total: "Итого",
    thresholdMet: "Норма",
    yes: "да",
    no: "нет",
    approve: "Утвердить",
    markPaid: "Отметить выплаченной",
    cancelSheet: "Отменить черновик",
    cancelConfirm: "Отменить черновик? Начисления будут откреплены и доступны для пересчёта.",
    createdBy: "Сформировал",
    createdAt: "Создано",
    linesCount: "Строк",
    status: "Статус",
  },
  support: {
    title: "Поддержка",
    tabTickets: "Тикеты",
    tabCalls: "Звонки",
    tabMessages: "Сообщения",
    tabNotifications: "Уведомления",
    // тикеты
    ticketsTitle: "Тикеты техподдержки",
    newTicket: "Новый тикет",
    number: "Номер",
    client: "Клиент",
    noClient: "Без клиента",
    contact: "Контакт",
    channel: "Канал",
    channels: {
      phone: "Телефон",
      whatsapp: "WhatsApp",
      telegram: "Telegram",
      email: "E-mail",
      site: "Сайт",
      manual: "Вручную",
      chat: "Чат",
      sms: "SMS",
      web_push: "Push",
    },
    subject: "Тема",
    description: "Описание",
    status: "Статус",
    ticketStatuses: {
      new: "Новый",
      in_progress: "В работе",
      on_service: "На обслуживании",
      done: "Решён",
      rejected: "Отклонён",
    },
    resolution: "Исход",
    resolutions: {
      remote: "Решено удалённо",
      service_requests: "Переданы заявки ТО",
      rejected: "Отклонён",
    },
    assigned: "Назначен",
    createdAt: "Создано",
    closedAt: "Закрыт",
    allStatuses: "Все статусы",
    allChannels: "Все каналы",
    allClients: "Все клиенты",
    apply: "Применить",
    takeInProgress: "Взять в работу",
    resolveRemote: "Решено удалённо",
    remoteConfirm: "Закрыть тикет как решённый удалённо?",
    toService: "Передать на обслуживание",
    reject: "Отклонить",
    rejectConfirm: "Отклонить тикет?",
    requestType: "Тип заявки",
    selectObjects: "Объекты клиента",
    createRequests: "Создать заявки",
    needObjects: "Выберите хотя бы один объект",
    needClient: "У тикета не указан клиент — передать на обслуживание нельзя",
    serviceHint: "По каждому выбранному объекту будет создана заявка ТО. Тикет перейдёт в «На обслуживании» и закроется автоматически после выполнения всех заявок.",
    linkedRequests: "Заявки ТО по тикету",
    // звонки
    callsTitle: "Журнал звонков",
    addCall: "Зафиксировать звонок",
    direction: "Направление",
    directions: { incoming: "Входящий", outgoing: "Исходящий", missed: "Пропущенный" },
    phone: "Телефон",
    request: "Заявка",
    durationSec: "Длительность, сек",
    result: "Результат",
    registeredBy: "Зафиксировал",
    // сообщения
    messagesTitle: "Журнал сообщений",
    addMessage: "Добавить заметку",
    text: "Текст",
    directionIn: "Входящее",
    directionOut: "Исходящее",
    // уведомления
    notificationsTitle: "Уведомления",
    tabQueue: "Очередь",
    tabTemplates: "Шаблоны",
    recipient: "Получатель",
    template: "Шаблон",
    attempts: "Попытки",
    lastError: "Ошибка",
    nextAttemptAt: "Следующая попытка",
    sentAt: "Отправлено",
    queueStatuses: {
      queued: "В очереди",
      sending: "Отправляется",
      sent: "Отправлено",
      failed: "Ошибка",
      cancelled: "Отменено",
    },
    sendNow: "Отправить сейчас",
    processed: "Обработано",
    cancelItem: "Отменить",
    addTemplate: "Добавить шаблон",
    editTemplate: "Изменить",
    code: "Код",
    subjectRu: "Тема (RU)",
    subjectKk: "Тема (KK)",
    bodyRu: "Текст (RU)",
    bodyKk: "Текст (KK)",
    active: "Активен",
  },
  reports: {
    title: "Отчёты",
    tabEquipment: "Оборудование",
    tabDays: "Дни в размещении",
    tabWorkload: "Загруженность",
    tabActivity: "Активность",
    // сводный по оборудованию
    equipmentTitle: "Оборудование по размещениям",
    buckets: {
      warehouse: "Склады",
      technician: "Техники",
      client: "Клиенты",
      testing: "Тестирование",
      supplier: "Поставщики",
      written_off: "Списано",
    },
    group: "Размещение",
    bucket: "Группа",
    newCount: "Новое",
    usedCount: "БУ",
    total: "Всего",
    details: "Расшифровка",
    collapse: "Свернуть",
    daysHere: "Дней в размещении",
    exportDetails: "Расшифровка в Excel",
    // отчёты «с днями»
    daysTitle: "Отчёты с днями",
    tabTesting: "На тестировании",
    tabFromClients: "Принято от клиентов",
    tabAtSupplier: "У поставщика",
    doc: "Документ",
    sinceDate: "С даты",
    days: "Дней",
    defect: "Неисправность",
    // загруженность
    workloadTitle: "Загруженность исполнителей (план/факт)",
    period: "Период",
    show: "Показать",
    performer: "Исполнитель",
    plannedOrders: "Нарядов назначено (план)",
    closedActs: "Актов закрыто (факт)",
    pieceAmount: "Сдельные начисления",
    // активность
    activityTitle: "Активность оборудования по клиентам",
    client: "Клиент",
    currentSlice: "Текущий срез, ед.",
    daysInMonth: "Дни за месяц (регистр состояний)",
    nowActive: "Активно",
    nowConservation: "Консервация",
    nowDisabled: "Отключено",
    activeDays: "Дни активности",
    conservationDays: "Дни консервации",
    billableDays: "Оплачиваемые дни",
  },
  dashboard: {
    title: "Главная",
    openRequests: "Открытые заявки",
    overdue: "Просроченные",
    ordersToday: "Нарядов сегодня",
    openTickets: "Открытые тикеты",
    syncErrors: "Ошибки синхронизации (24ч)",
    syncErrorsHint: "Есть ошибки — открыть журнал",
    billingMonth: "Биллинг месяца",
    billed: "Выставлено",
    paid: "Оплачено",
    documents: "Документов",
    paidShare: "Собираемость",
    topDebtors: "Топ-5 должников",
    debt: "Долг",
    allSettlements: "Вся ведомость",
    techBusy: "Занятость техников",
    ordersInWork: "нарядов в работе",
    equipmentTitle: "Оборудование",
    eqInstalled: "Установлено",
    eqInStock: "На складе",
    eqWithTech: "У техников",
    eqTesting: "На тесте",
    eqSupplier: "У поставщика",
    noData: "Нет данных",
  },
  clientCard: {
    scheme: "Схема расчётов",
    schemeAdvance: "Авансовая",
    schemeCredit: "Кредитная",
    category: "Категория",
    manager: "Менеджер",
    requisites: "Реквизиты",
    counterparty: "Контрагент",
    noCounterparty: "Контрагент не заполнен",
    legalAddress: "Юр. адрес",
    settlements: "Ведомость расчётов",
    park: "Парк клиента",
    object: "Объект",
    equipment: "Оборудование",
    state: "Состояние",
    telematics: "Телематика",
    smName: "Имя в СМ",
    reception: "Приём данных",
    recOn: "вкл",
    recOff: "выкл",
    noLink: "нет привязки",
    setState: "Установка состояния",
    stateActive: "Активен",
    stateConservation: "Консервация",
    stateDisabled: "Отключён",
    transferClient: "Перевод клиенту",
    moveObject: "Перенос на объект",
    targetClient: "Новый клиент",
    targetObject: "Объект",
    apply: "Выполнить",
    confirmTransfer: "Перевести оборудование другому клиенту? Биллинг продолжится у нового клиента.",
    confirmMove: "Перенести оборудование на другой объект этого клиента?",
    syncNote: "Команда в систему мониторинга выполняется по возможности; ошибка попадает в журнал синхронизации.",
    contracts: "Договоры",
    contractNumber: "Номер",
    kind: "Вид",
    validFrom: "С",
    validTo: "По",
    status: "Статус",
    recentDocs: "Последние документы биллинга",
    openRequests: "Открытые заявки",
    notFound: "Клиент не найден",
  },
  profile: {
    language: "Язык",
  },
  mobile: {
    title: "Рабочее место техника",
    brand: "ТЕХНИК",
    navHome: "Главная",
    navOrders: "Наряды",
    navStock: "Склад",
    navPayroll: "Заработок",
    documents: "Документы",
    reports: "Отчёты",
    myOrders: "Мои наряды",
    todayShort: "сегодня",
    weekShort: "неделя",
    schedule: "Расписание работ",
    myStock: "Мой склад",
    simCards: "SIM-карты",
    myEarnings: "Мой заработок",
    officeVersion: "Офисная версия",
    logout: "Выйти",
    push: {
      enable: "Включить уведомления",
      enabled: "Уведомления включены",
      denied: "Уведомления запрещены в браузере",
      unsupported: "Push не поддерживается на этом устройстве",
      error: "Не удалось включить уведомления",
    },
    filters: { today: "Сегодня", week: "Неделя", all: "Все" },
    order: {
      title: "Наряд",
      client: "Клиент",
      object: "Объект",
      address: "Адрес",
      period: "Период",
      note: "Примечание",
      request: "Заявка",
      call: "Позвонить",
      route2gis: "2ГИС",
      routeGeo: "Карты",
      performers: "Исполнители",
      acts: "Акты ТО",
      openAct: "Открыть акт",
      createAct: "Создать акт",
      noSchedule: "время не назначено",
      empty: "Нарядов нет",
    },
    steps: {
      title: "Ход выезда",
      depart: "Выехал",
      arrive: "Прибыл",
      start: "Начал работы",
      finish: "Завершил",
      cantDo: "Не могу выполнить",
      cantDoNote: "Укажите причину",
      geoWarn: "Геолокация недоступна — шаг записан без координат",
      names: {
        accept: "Принят",
        depart: "Выехал",
        arrive: "Прибыл",
        start: "Начал работы",
        finish: "Завершил",
        cant_do: "Не выполнен",
        repeat: "Повторный выезд",
      },
    },
    act: {
      title: "Акт ТО",
      main: "Основное",
      signerName: "Подписант от клиента",
      signerPlaceholder: "ФИО подписанта",
      saveSigner: "Сохранить",
      photos: "Фотофиксация",
      addPhoto: "Фото с камеры",
      signature: "Подпись клиента",
      drawHint: "Распишитесь пальцем в поле ниже",
      clear: "Очистить",
      saveSignature: "Сохранить подпись",
      signedAt: "Подписано",
      sendToOffice: "Отправить в офис",
      sentInfo: "Акт передан в офис. Закрытие акта выполняет офис — это норма процесса.",
      notEditable: "Акт больше не редактируется",
      myUnit: "Со своего склада",
      removedUnit: "Снято у клиента",
      forEquipment: "В оборудование",
    },
    stock: {
      title: "Мой склад",
      equipment: "Оборудование",
      sim: "SIM-карты",
      empty: "Пусто",
    },
    payroll: {
      title: "Мой заработок",
      currentMonth: "Текущий месяц",
      prevMonth: "Прошлый месяц",
      work: "Сдельные работы",
      compensation: "Компенсации",
      deduction: "Удержания",
      total: "Итого",
      entries: "Начисления",
      empty: "Начислений нет",
    },
  },
};

export type Dict = typeof ru;
